site:
  title: Documentation
content:
  sources:
  - url: ./
    branches: [v*, main]
    start_path: src
  - url: https://github.com/Netbeheer-Nederland/doc-linkml-modeling-guide
    branches: [v*, main]
    start_path: src
asciidoc:
  attributes:
    kroki-fetch-diagram: true
    kroki-default-format: svg@
  extensions:
  - asciidoctor-kroki
output:
  clean: true
  dir: ./docs
urls:
  latest_version_segment: latest
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
antora:
  extensions:
  - require: '@antora/lunr-extension'
