site:
  title: Netbeheer Nederland Documentation
  url: https://netbeheer-nederland.github.io/docs
content:
  # tags: ['v+({1..9}).+({0..9})', '!*-*']
  sources:
  - url: .
    branches: HEAD
    start_path: ./root_component
  - url: https://github.com/Netbeheer-Nederland/dp-meetdata
    branches: docs
    start_paths: [v*.*.*]
  - url: https://github.com/Netbeheer-Nederland/dp-transitietechnieken
    branches: docs
    start_paths: [v*.*.*]
  - url: https://github.com/Netbeheer-Nederland/dp-netburen
    branches: docs
    start_paths: [v*.*.*]
  - url: https://github.com/Netbeheer-Nederland/dp-capaciteitskaart
    branches: docs
    start_paths: [v*.*.*]
  - url: https://github.com/Netbeheer-Nederland/dp-netbewust-laden
    branches: docs
    start_paths: [v*.*.*]
asciidoc:
  attributes:
    page-pagination: ''
    experimental: ''
    kroki-fetch-diagram: true
    kroki-default-format: svg@
    kroki-server-url: http://fruit.ritger.nl:9000
  extensions:
  - asciidoctor-kroki
output:
  clean: true
  dir: ./docs
urls:
  latest_version_segment: latest
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
antora:
  extensions:
  - require: '@antora/lunr-extension'
