= Representing UML Class Diagrams in LinkML

== Transformations

=== Multiplicities
==== General cardinality restrictions

|===
|UML| LinkML

| `0..1`
a|
[source,yaml]
....
# Default.
....

| `0..\*` / `*` / _not specified_
a|
[source,yaml]
....
multivalued: true
....

| `1`
a|
[source,yaml]
....
required: true
....

| `1..*`
a|
[source,yaml]
....
required: true
multivalued: true
....

|===

==== More specific cardinality restrictions

|===
|UML| LinkML

| `i`

where `i > 1` and `i ≠ *`
a|
[source,yaml]
....
exact_cardinality: i
# required: true
# multivalued: true
....

a| `i..*`

where `i > 1`
a|
[source,yaml]
....
minimum_cardinality: i
multivalued: true
# required: true
....

a| `0..j`

where `j > 1` and `j ≠ *`
a|
[source,yaml]
....
maximum_cardinality: j
# multivalued: true
....

a| `i..j`

where `i, j > 1` and `i, j ≠ *`

a|
[source,yaml]
....
minimum_cardinality: i
maximum_cardinality: j
# required: true
# multivalued: true
....

|===

NOTE: The commented lines in the LinkML column are values that should be implied, but since not all generators and software will understand more specific cardinality values, it can be wise to explicitly add the `required` and `multivalued` statements as well.

=== Classes

|===
|UML |LinkML

a|
.Class
[plantuml,width=100px]
....
@startuml
class C
@enduml
....

a|
[source,yaml]
....
classes:
  C:
....

a|
.Class with attributes
[plantuml,width=100px]
----
@startuml
class C
C : a: t [i..j]
@enduml
----

a|
[source,yaml]
....
classes:
  C:
    attributes:
      a:
....

Then, for each attribute:

* Add a range by mapping `t` to a suited LinkML data type by following: <<Data types>>.
* Add cardinality restrictions based on the multiplcity `i..j` following: <<Multiplicities>>.

|===

=== Relations

==== Specialization

|===
|UML |LinkML

a|
[plantuml,width=100px]
----
@startuml
class C
class D
C <\|-- D
@enduml
----

// where `r~C~` is the role played by `C` in the relation `R` (analogously for `r~D~`).

a|
[source,yaml]
----
classes:
  C:
  D:
    is_a: C
----

|===

==== Associations

|===
|UML |LinkML

a|.Standard association (bidirectional)
[plantuml,width=100px]
----
@startuml
class C
class D
C "r<sub>C</sub>" -- "r<sub>D</sub>" D: R
@enduml
----

// where `r~C~` is the role played by `C` in the relation `R` (analogously for `r~D~`).

a|
[source,yaml]
....
classes:
  C:
    slots:
    - C.r_D
  D:
    slots:
    - D.r_C

slots:
  C.r_D:
    range: D
    inverse: D.r_C
  D.r_C:
    range: C
    inverse: C.r_D
....

a|
.Standard association (unidirectional)
[plantuml,width=100px]
----
@startuml
class C
class D
C "r<sub>C</sub>" --> "r<sub>D</sub>" D: R
@enduml
----

a|
[source,yaml]
....
classes:
  C:
    slots:
    - C.r_D
  D:

slots:
  C.r_D:
    range: D
....

////
[d2,width=50%]
----
C: C {
  shape: class
}
D: D {
  shape: class
}
C -- D: r {
  source-arrowhead: i..j
  target-arrowhead: k..l
}
----
////

a|
[plantuml,width=100px]
----
@startuml
class C
class D
C "i..j" -- "k..l" D: R
@enduml
----

a|
[source,yaml]
....
classes:
  C:
    slots:
      - C.r
  D:
    slots:
      - D.r
slots:
  C.r:
    domain: C
    range: D
    minimum_cardinality: k
    maximum_cardinality: l
    inverse: D.r
  D.r:
    domain: D
    range: C
    minimum_cardinality: i
    maximum_cardinality: j
    inverse: C.r
....

a|.Standard association (bidirectional)
[plantuml,width=100px]
----
@startuml
class C
class D
C "r<sub>C</sub> [k..l]" -- "r<sub>D</sub> [i..j]" D: R
@enduml
----

// where `r~C~` is the role played by `C` in the relation `R` (analogously for `r~D~`).

a|
[source,yaml]
....
classes:
  C:
    slots:
    - C.r_D
  D:
    slots:
    - D.r_C

slots:
  C.r_D:
    range: D
    inverse: D.r_C
  D.r_C:
    range: C
    inverse: C.r_D
....

Then, for each slot:

* Add cardinality restrictions following: <<Multiplicities>>.


a|
.Standard association (unidirectional)
[plantuml,width=100px]
----
@startuml
class C
class D
C -- "i..j" D: R
@enduml
----

a|
[source,yaml]
....
classes:
    C:
      attributes:
        r:
          range: D
          minimum_cardinality: i
          maximum_cardinality: j
    D:
....

or


[source,yaml]
....
classes:
  C:
    slots:
    - C.r
  D:
slots:
  C.r:
    domain: C
    range: D
    minimum_cardinality: i
    maximum_cardinality: j
....

|===

===== Aggregations and compositions

|===
| UML | LinkML

a|
.Aggregation
[plantuml,width=100px]
----
@startuml
class C
class D
C *-- D
@enduml
----

or

.Composition
[plantuml,width=100px]
----
@startuml
class C
class D
C o-- D
@enduml
----

a|
[source,yaml]
....
classes:
  C:
    attributes:
    r:
      range: D
      inlined_as_list: true
  D:
....

or

[source,yaml]
....
classes:
  C:
    slots:
    - C.r:
  D:
slots:
  C.r:
    domain: C
    range: D
    inlined_as_list: true
....

|===

=== Data types

=== Enumerations

|===
|UML |LinkML

a|
.Enumeration class
[d2,width=50%]
----
E: "<<enumeration>> E" {
  shape: class
  +
}
----

a|
[source,yaml]
....
classes:
  C:
....

|===

== Assumptions and decisions

* When stronger statements imply weaker statements, but the inference is not supported broadly, prefer to be explicit and assert the weaker statements as well.
* All associations are top-level slots, even those that are unidirectional.
** Bidirectional associations need to be represented as top-level slots since the two slots representing them need to be stated to be each other's inverse.
** Having all associations be top-level slots ensures consistency and reduces cognitive load and confusion.
** Also: `attributes` are actually (and only) attributes.
** In the case of the CIM this actually lines up nicely with the URIs assigned to relations, e.g. the slot `Terminal.ConductingEquipments` will have the URI `cim:TerminalConductingEquipments`. Again: consistency and reduction of cognitive load.



== N-ary relations

== Linked Data URIs




[bibliography]
== References
* [[[SCENARIO-TESTING-USING-OWL]]] Hendrina Harmse. https://api.semanticscholar.org/CorpusID:58132703[Scenario testing using OWL]. 2015.
* [[[HARMSE]]] https://henrietteharmse.com/wp-content/uploads/2017/11/uml-class-diagram-to-owl-and-sroiq-reference.pdf[UML Class Diagram to OWL and SROIQ Reference] -- Henriette Harmse (2017)
* [[[LINKML-FAQ]]] https://linkml.io/linkml/faq/modeling.html#when-two-data-classes-are-linked-by-a-slot-in-one-class-definition-how-is-the-reciprocal-association-expressed-in-linkml[LinkML FAQ: When two data classes are linked by a slot in one class definition, how is the reciprocal association expressed in LinkML?]

== See also
* https://github.com/Sveino/Inst4CIM-KG/issues/146