= Representing UML Class Diagrams in LinkML

== Transformations

=== Multiplicities
==== General cardinality restrictions

|===
|UML| LinkML

| `0..1`
a|
[source,yaml]
....
# Default.
....

| `0..\*` / `*` / _not specified_
a|
[source,yaml]
....
multivalued: true
....

| `1`
a|
[source,yaml]
....
required: true
....

| `1..*`
a|
[source,yaml]
....
required: true
multivalued: true
....

|===

==== More specific cardinality restrictions

|===
|UML| LinkML

| `i`

where `i > 1` and `i ≠ *`
a|
[source,yaml]
....
exact_cardinality: i
# required: true
# multivalued: true
....

a| `i..*`

where `i > 1`
a|
[source,yaml]
....
minimum_cardinality: i
multivalued: true
# required: true
....

a| `0..j`

where `j > 1` and `j ≠ *`
a|
[source,yaml]
....
maximum_cardinality: j
# multivalued: true
....

a| `i..j`

where `i, j > 1` and `i, j ≠ *`

a|
[source,yaml]
....
minimum_cardinality: i
maximum_cardinality: j
# required: true
# multivalued: true
....

|===

NOTE: The commented lines in the LinkML column are values that should be implied, but since not all generators and software will understand more specific cardinality values, it can be wise to explicitly add the `required` and `multivalued` statements as well.

=== Classes

|===
|UML |LinkML

a|
.Class
[plantuml,width=100px]
....
@startuml
class C
@enduml
....

a|
[source,yaml]
....
classes:
  C:
....

a|
.Class with attributes
[plantuml,width=100px]
----
@startuml
class C
C : a: t [i..j]
@enduml
----

a|
[source,yaml]
....
classes:
  C:
    attributes:
      a:
....

Then, for each attribute:

* Add a range by mapping `t` to a suited LinkML data type by following: <<Data types>>.
* Add cardinality restrictions based on the multiplcity `i..j` following: <<Multiplicities>>.

|===

=== Relations

==== Specialization

|===
|UML |LinkML

a|
[plantuml,width=100px]
----
@startuml
class C
class D
C <\|-- D
@enduml
----

a|
[source,yaml]
----
classes:
  C:
  D:
    is_a: C
----

|===

==== Associations

|===
|UML |LinkML

a|.Standard association (bidirectional)
[plantuml,width=100px]
----
@startuml
class C
class D
C "r<sub>C</sub>" -- "r<sub>D</sub>" D: R
@enduml
----

a|
[source,yaml]
....
classes:
  C:
    slots:
    - C.r_D
  D:
    slots:
    - D.r_C

slots:
  C.r_D:
    domain: C
    range: D
    inverse: D.r_C
  D.r_C:
    domain: D
    range: C
    inverse: C.r_D
....

a|
.Standard association (unidirectional)
[plantuml,width=100px]
----
@startuml
class C
class D
C --> "r<sub>D</sub>" D: R
@enduml
----

a|
[source,yaml]
....
classes:
  C:
    slots:
    - C.r_D
  D:

slots:
  C.r_D:
    domain: C
    range: D
....

a|
.Aggregation
[plantuml,width=100px]
----
@startuml
class C
class D
C o-- "r<sub>D</sub>" D: R
@enduml
----

a|
[source,yaml]
....
classes:
  C:
    slots:
    - C.r_D
  D:

slots:
  C.r_D:
    domain: C
    range: D
....

a|
.Composition
[plantuml,width=100px]
----
@startuml
class C
class D
C *-- "r<sub>D</sub>" D: R
@enduml
----

a|
[source,yaml]
....
classes:
  C:
    slots:
    - C.r_D
  D:

slots:
  C.r_D:
    domain: C
    range: D
    inlined_as_list: true
....

|===

==== N-ary relations

#TODO#: Association class that maps to a LinkML class with `represents_relationship: true`.

==== Multiplicities
Mapping multiplicities to LinkML cardinality restrictions is described in <<Multiplicities>>.

=== Enumerations

|===
|UML |LinkML

a|
.Enumeration class
[plantuml,width=100px]
----
enum E {
  V
}
----

a|
[source,yaml]
....
enums:
  E:
    permissible_values:
      V:
....

|===

=== Data types

==== CIM primitives

|===
| UML  | LinkML

| `Float`
| https://linkml.io/linkml-model/latest/docs/Date/[`float`]

| `Integer`
| `integer`

| `DateTime`
| `date`

| `String`
| `string`

| `Boolean`
| `boolean`

| `Decimal`
| `double`

| `MonthDay`
| `date`

| `Date`
| `date`

|===

==== CIM data types

CIM data types are UML classes of stereotype `CIMDatatype`.


[NOTE]
--
In future versions the aim is to replace the CIM data types with quantity kinds, units, etc. from the QUDT ontology.

These data types might then be represented as custom LinkML types if desired.
--

|===
| UML  | LinkML

| `ActivePower`
| `float`

| `ActivePowerChangeRate`
| `float`

| `ActivePowerPerCurrentFlow`
| `float`

| `ActivePowerPerFrequency`
| `float`

| `Admittance`
| `float`

| `AngleDegrees`
| `float`

| `AngleRadians`
| `float`

| `ApparentPower`
| `float`

| `Area`
| `float`

| `Bearing`
| `float`

| `Capacitance`
| `float`

| `CapacitancePerLength`
| `float`

| `Classification`
| `float`

| `Conductance`
| `float`

| `ConductancePerLength`
| `float`

| `CostPerEnergyUnit`
| `float`

| `CostPerHeatUnit`
| `float`

| `CostPerVolume`
| `float`

| `CostRate`
| `float`

| `CurrentFlow`
| `float`

| `Damping`
| `float`

| `Displacement`
| `float`

| `Emission`
| `float`

| `Frequency`
| `float`

| `HeatRate`
| `float`

| `Hours`
| `float`

| `Impedance`
| `float`

| `Inductance`
| `float`

| `InductancePerLength`
| `float`

| `KiloActivePower`
| `float`

| `Length`
| `float`

| `MagneticField`
| `float`

| `Mass`
| `float`

| `Minutes`
| `float`

| `Money`
| `float`

| `ParticulateDensity`
| `float`

| `PerCent`
| `float`

| `Pressure`
| `float`

| `PU`
| `float`

| `Reactance`
| `float`

| `ReactancePerLength`
| `float`

| `ReactivePower`
| `float`

| `RealEnergy`
| `float`

| `Resistance`
| `float`

| `ResistancePerLength`
| `float`

| `RotationSpeed`
| `float`

| `Seconds`
| `float`

| `Speed`
| `float`

| `Susceptance`
| `float`

| `SusceptancePerLength`
| `float`

| `Temperature`
| `float`

| `Voltage`
| `float`

| `VoltagePerReactivePower`
| `float`

| `Volume`
| `float`

| `VolumeFlowRate`
| `float`

| `WaterLevel`
| `float`

|===


== Assumptions and decisions

* When stronger statements imply weaker statements, but the inference is not supported broadly, prefer to be explicit and assert the weaker statements as well.
* All associations are top-level slots, even those that are unidirectional.
** Bidirectional associations need to be represented as top-level slots since the two slots representing them need to be stated to be each other's inverse.
** Having all associations be top-level slots ensures consistency and reduces cognitive load and confusion.
** Also: `attributes` are actually (and only) attributes.
** In the case of the CIM this actually lines up nicely with the URIs assigned to relations, e.g. the slot `Terminal.ConductingEquipments` will have the URI `cim:TerminalConductingEquipments`. Again: consistency and reduction of cognitive load.
* Aggregations are not inlined, whereas compositions are.




== Linked Data URIs




[bibliography]
== References
* [[[SCENARIO-TESTING-USING-OWL]]] Hendrina Harmse. https://api.semanticscholar.org/CorpusID:58132703[Scenario testing using OWL]. 2015.
* [[[HARMSE]]] https://henrietteharmse.com/wp-content/uploads/2017/11/uml-class-diagram-to-owl-and-sroiq-reference.pdf[UML Class Diagram to OWL and SROIQ Reference] -- Henriette Harmse (2017)
* [[[LINKML-FAQ]]] https://linkml.io/linkml/faq/modeling.html#when-two-data-classes-are-linked-by-a-slot-in-one-class-definition-how-is-the-reciprocal-association-expressed-in-linkml[LinkML FAQ: When two data classes are linked by a slot in one class definition, how is the reciprocal association expressed in LinkML?]
* [[[IBM-DEV-CLASS-DIAGRAM]]] https://developer.ibm.com/articles/the-class-diagram/#associations9
* [[[SPARX-UML-TUTORIAL-CLASS-DIAGRAM]]] https://sparxsystems.com/resources/tutorials/uml2/class-diagram.html

== See also
* https://github.com/Sveino/Inst4CIM-KG/issues/146
*